services:
  - type: web
    name: flask-gemini-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-pro
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "false"
